import { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useSelector } from 'react-redux';
import CodeViewer from './CodeViewer';
import { downloadZip, downloadPatch } from '../services/file.service';

export default function ResultScreen() {
  const { key } = useParams();
  const navigate = useNavigate();
  const result = useSelector((s) => s.issues.generationResult);
  const settings = useSelector((s) => s.settings);

  const [activeTab, setActiveTab] = useState(0);
  const [jiraStatus, setJiraStatus] = useState(null); // { type: 'success'|'error', message }
  const [sendingToJira, setSendingToJira] = useState(false);
  const [zipStatus, setZipStatus] = useState(null);

  // ── Guard ──
  if (!result) {
    return (
      <div className="empty-state">
        <div className="empty-icon">⚠️</div>
        <h2>No generation result available</h2>
        <p>Please go back and generate code first.</p>
        <button className="btn btn-primary" onClick={() => navigate(`/issue/${key}`)}>
          ← Back to {key}
        </button>
      </div>
    );
  }

  const { summary, files = [], patch } = result;
  const PATCH_TAB_IDX = files.length; // one extra tab at end if patch exists
  const hasPatch = !!patch;

  // ── Handlers ──
  async function handleDownloadZip() {
    setZipStatus(null);
    try {
      const res = await downloadZip(files, key);
      if (res.success) {
        setZipStatus({ type: 'success', message: `Saved to ${res.filePath}` });
      } else if (!res.cancelled) {
        setZipStatus({ type: 'error', message: 'Failed to save ZIP.' });
      }
    } catch (err) {
      setZipStatus({ type: 'error', message: err.message });
    }
  }

  async function handleDownloadPatch() {
    try {
      await downloadPatch(patch, key);
    } catch (err) {
      alert(`Failed to save patch: ${err.message}`);
    }
  }

  async function handleSendToJira() {
    setSendingToJira(true);
    setJiraStatus(null);
    try {
      const commentText = [
        `🤖 *AI-Generated Code Summary for ${key}*`,
        '',
        summary,
        '',
        `*Generated files (${files.length}):*`,
        ...files.map((f) => `• ${f.name}`),
        '',
        '_Generated by AI Dev Assistant — requires developer review before use._',
      ].join('\n');

      const res = await window.electronAPI.sendJiraComment({
        jiraUrl: settings.jiraUrl,
        jiraEmail: settings.jiraEmail,
        jiraToken: settings.jiraToken,
        issueKey: key,
        comment: commentText,
      });

      setJiraStatus(
        res.success
          ? { type: 'success', message: '✅ Comment posted to Jira successfully.' }
          : { type: 'error', message: `❌ Jira error: ${res.error}` }
      );
    } catch (err) {
      setJiraStatus({ type: 'error', message: err.message });
    } finally {
      setSendingToJira(false);
    }
  }

  // ── Render ──
  return (
    <div className="page">
      {/* ── Header ── */}
      <div className="page-header">
        <button className="btn btn-ghost" onClick={() => navigate(`/issue/${key}`)}>
          ← Back to {key}
        </button>
        <h1>Generated Code — {key}</h1>
      </div>

      {/* ── Summary + file list ── */}
      <div className="result-overview">
        <div className="summary-card">
          <h3>📋 Summary</h3>
          <p>{summary || 'No summary provided.'}</p>
        </div>

        <div className="files-card">
          <h3>📁 Files ({files.length})</h3>
          <ul className="file-index">
            {files.map((f, i) => (
              <li
                key={i}
                className={`file-index-item${activeTab === i ? ' active' : ''}`}
                onClick={() => setActiveTab(i)}
              >
                <span className="file-index-icon">📄</span>
                <span className="file-index-name">{f.name}</span>
              </li>
            ))}
            {hasPatch && (
              <li
                className={`file-index-item${activeTab === PATCH_TAB_IDX ? ' active' : ''}`}
                onClick={() => setActiveTab(PATCH_TAB_IDX)}
              >
                <span className="file-index-icon">🔀</span>
                <span className="file-index-name">patch.diff</span>
              </li>
            )}
          </ul>
        </div>
      </div>

      {/* ── Code viewer ── */}
      <div className="code-section">
        {/* Tab bar */}
        <div className="tab-bar" role="tablist">
          {files.map((f, i) => (
            <button
              key={i}
              role="tab"
              aria-selected={activeTab === i}
              className={`tab${activeTab === i ? ' tab--active' : ''}`}
              onClick={() => setActiveTab(i)}
            >
              {f.name.split('/').pop()}
            </button>
          ))}
          {hasPatch && (
            <button
              role="tab"
              aria-selected={activeTab === PATCH_TAB_IDX}
              className={`tab${activeTab === PATCH_TAB_IDX ? ' tab--active' : ''}`}
              onClick={() => setActiveTab(PATCH_TAB_IDX)}
            >
              🔀 patch.diff
            </button>
          )}
        </div>

        {/* Code panel */}
        {activeTab < files.length && files[activeTab] && (
          <CodeViewer filename={files[activeTab].name} content={files[activeTab].content} />
        )}
        {activeTab === PATCH_TAB_IDX && hasPatch && (
          <CodeViewer filename="patch.diff" content={patch} language="diff" />
        )}
      </div>

      {/* ── Status messages ── */}
      {zipStatus && (
        <div className={`alert alert-${zipStatus.type}`}>{zipStatus.message}</div>
      )}
      {jiraStatus && (
        <div className={`alert alert-${jiraStatus.type}`}>{jiraStatus.message}</div>
      )}

      {/* ── Action bar ── */}
      <div className="action-bar">
        <button
          className="btn btn-success"
          onClick={handleDownloadZip}
          disabled={files.length === 0}
        >
          📦 Download ZIP
        </button>

        <button
          className="btn btn-secondary"
          onClick={handleDownloadPatch}
          disabled={!hasPatch}
          title={!hasPatch ? 'No patch was returned by the AI' : undefined}
        >
          🔀 Download PATCH
        </button>

        <button
          className="btn btn-primary"
          onClick={handleSendToJira}
          disabled={sendingToJira}
        >
          {sendingToJira ? 'Sending…' : '📨 Send to Jira'}
        </button>
      </div>
    </div>
  );
}
